# Assignment for week 4

Use the following table to provide us with

|name | exam number|
|----|----|
|David van Son| u335946|
|Jacques Mcdermott| u554837|

In this assignment, we will play around with functions and use the `fsolve` routine to solve an equation.

First, we need to import some libraries.

Recall that you need to have installed plotly for this to work. Further, you need to register at the plotly website.

In [2]:
from scipy import optimize

from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
from plotly.graph_objs import Bar, Scatter, Figure, Layout
init_notebook_mode(connected=True)
from numpy import arange


Let us define the function $f(x) = x^2+c$ which is a function of $x$ for a given value of $c$.

In [2]:
def my_function(x,c):
    return x**2 + c

Now we would like to solve $x^2 + c =0$. As this is a simple equation, you can this analytically. This helps us to understand how `fsolve` works.

If you want to know more about `fsolve`, simply google "python fsolve".

For our purposes here, we call `fsolve` as `optimize.fsolve`, then we give a function and an initial value where `fsolve` starts looking for a solution. `fsolve` uses numerical techniques to find the "zero" of a function; it does not solve the equation analytically. Roughly speaking, it looks at a value of $x$ whether it is above or below 0. If it is below 0, it needs to change $x$ in such a way that $f(x)$ increases. It uses the derivative $f'(x)$ to figure out whether it should increase or decrease $x$ to get to $f(x)=0$. So suppose that $f(x) < 0$ and $f'(x) >0$ then it will increase $x$ (move to the right) to a solution to $f(x) =0$.

As `my_function` is actually a function of two variables ($x$ and $c$), we define a new "anonymous" function `lambda` that is only a function of $x$ and we solve for this function to 0. Say, we start looking for a solution at $x=1$, then we type:

In [3]:
optimize.fsolve(lambda x: my_function(x,-2),+1)

array([ 1.41421356])

This only gives one solution? But with a quadratic equation, there are usually two solutions. In the following cell give the python command to give the other solution:

In [3]:
optimize.fsolve(lambda x: my_function(x,-2),-1)

array([-1.41421356])

Now try the following cell. Explain below why you get an error message; $x=0$ does not solve this equation?

In [6]:
optimize.fsolve(lambda x: my_function(x,-2),0)

C:\Users\dvdva\Good anaconda\lib\site-packages\scipy\optimize\minpack.py:161: RuntimeWarning:

The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.



array([ 0.])

Type your explanation here: the derivative of x^2 equals 2x. If x is 0 the derivative is 0. This means that we cannot use the derivative to figure out if we should increase or decrease on x to get to f(x)= 0 because the derivative is always the same

Now we let's consider another function, with $c = 2$ (instead of $c = -2$). Explain below why we get an error this time

In [11]:
optimize.fsolve(lambda x: my_function(x,2),-1)

C:\Users\dvdva\Good anaconda\lib\site-packages\scipy\optimize\minpack.py:161: RuntimeWarning:

The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.



array([-0.00097656])

Type your explanation here: if C is positive then x^2 has to be negative to make f(x)=0. A x squared can never be negative so that is why there is an error.

Now define the function $f(x) = \frac{1}{x}$ in python:

In [12]:
def my_function(x,c):
    return 1/x

and use plotly to plot this function for $x > 0$. Adjust the range for $x$ so that you get a "decent" graph.

In [15]:
range_x = arange(1,100)
iplot([{"x": range_x, "y": [1/x for x in range_x]}])